### ISSUE TITLE
cargo test --release fails

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/maidsafe_client#102]
willie@gagarin:~/projects/maidSafe/maidsafe_nfs$ cargo test --release --verbose
       Fresh rustc-serialize v0.3.15
       Fresh regex-syntax v0.2.0
       Fresh winapi-build v0.1.0
       Fresh gcc v0.3.8
       Fresh byteorder v0.3.11
       Fresh libc v0.1.8
       Fresh strsim v0.3.0
       Fresh itertools v0.3.22
       Fresh cbor v0.3.7
       Fresh rand v0.3.8
       Fresh num_cpus v0.2.6
       Fresh memchr v0.1.3
       Fresh winapi v0.1.23
       Fresh libsodium-sys v0.0.5
       Fresh log v0.3.1
       Fresh num v0.1.25
       Fresh tempdir v0.3.4
       Fresh asynchronous v0.4.5
       Fresh aho-corasick v0.2.2
       Fresh sodiumoxide v0.0.5
       Fresh kernel32-sys v0.1.2
       Fresh regex v0.1.40
       Fresh time v0.1.30
       Fresh term v0.2.10
       Fresh env_logger v0.3.1
       Fresh docopt v0.6.67
       Fresh message_filter v0.1.2
       Fresh rust-crypto v0.2.31
       Fresh lru_time_cache v0.2.0
       Fresh utp v0.6.0
       Fresh self_encryption v0.2.1
       Fresh accumulator v0.0.3
       Fresh crust v0.1.5
       Fresh routing v0.2.8
       Fresh maidsafe_types v0.2.3
       Fresh maidsafe_client v0.1.2
       Fresh maidsafe_nfs v0.0.1 (file:///home/willie/projects/maidSafe/maidsafe_nfs)
     Running `/home/willie/projects/maidSafe/maidsafe_nfs/target/release/maidsafe_nfs-a01e031dd65e6eb2`

running 19 tests
test directory_info::test::serialise ... ok
test directory_listing::test::serialise ... ok
test file::test::serialise ... ok
test helper::directory_helper::test::create_dir_listing ... ok
test metadata::test::serialise ... ok
test rest::blob::test::compare ... ok
test rest::blob::test::convert_to_file ... ok
test rest::blob::test::create ... ok
test rest::blob::test::create_from_file ... ok
test helper::directory_helper::test::update_and_versioning ... FAILED
test helper::directory_helper::test::get_dir_listing ... FAILED
test helper::file_helper::test::create_read_update ... FAILED
test rest::container::test::create_update_delete_blob ... FAILED
test rest::container_info::test::convert_from ... ok
test rest::container_info::test::convert_to ... ok
test rest::container_info::test::create ... ok
test rest::container::test::create_container ... FAILED
test rest::container::test::authorise_container ... FAILED
test rest::container::test::delete_container ... FAILED

failures:

---- helper::directory_helper::test::update_and_versioning stdout ----
	thread 'helper::directory_helper::test::update_and_versioning' panicked at 'called `Result::unwrap()` on an `Err` value: Decode(Other("Expected Unicode string or variant map, but got Int8"))', ../src/libcore/result.rs:731

---- helper::directory_helper::test::get_dir_listing stdout ----
	thread 'helper::directory_helper::test::get_dir_listing' panicked at 'called `Result::unwrap()` on an `Err` value: AtOffset { kind: Unassigned { major: 7, add: 11 }, offset: 0 }', ../src/libcore/result.rs:731

---- helper::file_helper::test::create_read_update stdout ----
	thread 'helper::file_helper::test::create_read_update' panicked at 'called `Result::unwrap()` on an `Err` value: AtOffset { kind: InvalidAddValue { ty: Int, val: 31 }, offset: 1 }', ../src/libcore/result.rs:731

---- rest::container::test::create_update_delete_blob stdout ----
	thread 'rest::container::test::create_update_delete_blob' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362

---- rest::container::test::create_container stdout ----
	thread 'rest::container::test::create_container' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362

---- rest::container::test::authorise_container stdout ----
	thread 'rest::container::test::authorise_container' panicked at 'called `Result::unwrap()` on an `Err` value: AtOffset { kind: InvalidAddValue { ty: UInt, val: 31 }, offset: 0 }', ../src/libcore/result.rs:731

---- rest::container::test::delete_container stdout ----
	thread 'rest::container::test::delete_container' panicked at 'called `Result::unwrap()` on an `Err` value: Decode(Other("Expected Unicode string or variant map, but got Tag"))', ../src/libcore/result.rs:731

failures:
    helper::directory_helper::test::get_dir_listing
    helper::directory_helper::test::update_and_versioning
    helper::file_helper::test::create_read_update
    rest::container::test::authorise_container
    rest::container::test::create_container
    rest::container::test::create_update_delete_blob
    rest::container::test::delete_container

test result: FAILED. 12 passed; 7 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:255

**Comment by ustulation** [comment]
not very different from already open issue:
https://github.com/maidsafe/maidsafe_client/issues/62

Closing..
