### ISSUE TITLE
Example: rest_api - panics when listing container versions

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/maidsafe_client#66]
BTW this is awesome :)

I had created container called "test", blob called "testblob" with content "a test file" and then did:
- list containers, OK
- list blobs, OK
- get blob content, OK
- get container versions, "Panic" as here...

List of container versions
	 No. 	 Version Id
	 === 	 ==========
	 1 	 "8\u{bc}\u{c9}j..\u{b7}i\u{bf}C"
thread '<main>' panicked at 'arithmetic operation overflowed', examples/rest_api.rs:119

**Comment by krishnaIndia** [comment]
Thanks @theWebalyst, for testing it. I will look into this issue and resolve it soon
