### ISSUE TITLE
Indicate Prequisites Required Libsodium

### ISSUE THREAD

**Issue by mwaa** [maidsafe/maidsafe_client#69]
Libsodium is a required perquisite. Can you indicate so with basic instructions on including it in the project folder before running Cargo test --release.

For windows, download and use the prebuilt mingw library. Extract and place the libsodium.a file in "bin\x86_64-pc-windows-gnu" for 64bit System, or "bin\i686-pc-windows-gnu" for a 32bit system.

**Comment by krishnaIndia** [comment]
Thanks @mwaa, We will add it to the readme.md. Thanks again for pointing it out. 

Cheers :)
