### ISSUE TITLE
Leading 0's not allowed for PIN - Should be allowed

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/maidsafe_client#73]
latest libs - last nights rust Ubuntu 15.04

<code>
willie@gagarin:~/projects/MaidSafe/maidsafe_client/target/debug/examples$ ./rest_api 

	Account Creation
	================

------------ Enter Keyword ---------------
me 

------------ Enter Password --------------
you

--------- Enter PIN (4 Digits) -----------
0000
ERROR: PIN is not 4 Digits !!

--------- Enter PIN (4 Digits) -----------
0123
ERROR: PIN is not 4 Digits !!

--------- Enter PIN (4 Digits) -----------
1234

Trying to create an account ...
Account Created Successfully !!

	Auto Account Login
	==================

Trying to log into the created account using supplied credentials ...
Account Login Successful !!

	-- Preparing storage ----

------  (Tip) Start by creating a container and then store blob, modify blob within the container --------------------

----------Choose an Operation----------------
</code>

I have tried this several times,  all with similar results

**Comment by ustulation** [comment]
@southsideGLA , thanks. Pull Request raised:
https://github.com/maidsafe/maidsafe_client/pull/74
once that is merged, should be fine.
