### ISSUE TITLE
Client doesn't bootstrap

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/maidsafe_client#81]
Just before [this point](https://github.com/maidsafe/maidsafe_client/blob/master/src/client/mod.rs#L96) we need to connect to the network by calling something like

    cloned_routing_client.lock().unwrap().bootstrap(None, None);

See https://github.com/maidsafe/routing/blob/master/src/routing_client.rs#L201-L204.

**Comment by dirvine** [comment]
Yes removing unwraps properly with error types will almost scream this
issue at us

On Sat, Jun 20, 2015 at 12:31 AM, Fraser Hutchison <notifications@github.com
> wrote:

> Just before this point
> <https://github.com/maidsafe/maidsafe_client/blob/master/src/client/mod.rs#L96>
> we need to connect to the network by calling something like
>
> cloned_routing_client.lock().unwrap().bootstrap(None, None);
>
> See
> https://github.com/maidsafe/routing/blob/master/src/routing_client.rs#L201-L204
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maidsafe/maidsafe_client/issues/81>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me
